- hosts: edge
  become: true

  vars:


  tasks:
    - name: Check Directories
      file:
        path: /usr/local/hms-mirror/bin
        state: directory

    - name: Check Directories
      file:
        path: /usr/local/hms-mirror/lib
        state: directory

    - name: Copy bin
      copy:
        src: hms-mirror
        dest: /usr/local/hms-mirror/bin
        mode: 0755


    - name: Copy lib
      copy:
        src: ../target/hms-mirror-shaded.jar
        dest: /usr/local/hms-mirror/lib
        mode: 0755

    - name: Copy No Hadoop lib
      copy:
        src: ../target/hms-mirror-shaded-no-hadoop.jar
        dest: /usr/local/hms-mirror/lib
        mode: 0755

    - name: Link executable
      file:
        src: /usr/local/hms-mirror/bin/hms-mirror
        dest: /usr/local/bin/hms-mirror
        mode: 0755
        state: link

