# Config
transferDbPrefix: "transfer_"
exportBaseDirPrefix: "/apps/hive/warehouse/export_"
overwriteTable: "true"
clusters:
  LOWER:
    # Set for Hive 1/2 environments
    legacyHive: "true"
    hcfsNamespace: "<hdfs://namespace>"
    hiveServer2:
      jarFile: "<environment-specific-jdbc-standalone-driver>"
      uri: "<lower-cluster-jdbc-url>"
      # Optional when using Kerberos Auth (Requires Kerb Ticket)
      connectionPropertites:
        user: "<user>"
        password: "<password>"
  UPPER:
    legacyHive: "false"
    hcfsNamespace: "<hdfs://namespace>"
    partitionDiscovery:
      # Addition HMS configuration needed for this "discover.partitions"="true"
      #     Set by default on IMPORT EXTERNAL.
      auto: true
      initMSCK: true
    hiveServer2:
      jarFile: "<environment-specific-jdbc-standalone-driver>"
      uri: "<upper-cluster-jdbc-url>"
      # Optional when using Kerberos Auth (Requires Kerb Ticket)
      connectionProperties:
        user: "<username>"
        password: "<password>"
